//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class AcountBook : Entity
    {
        public AcountBook()
        {
          this.AccoutBookNo= string.Empty;
          this.AccountDate= DateTime.Now;
          this.SubjectsCD= string.Empty;
          this.SubjectsDetails= string.Empty;
          this.Abstract= string.Empty;
          this.Direction= string.Empty;
          this.VoucherDate= DateTime.Now;
          this.CompanyCD= string.Empty;
          this.AttestBillNo= string.Empty;
          this.FormTBName= string.Empty;
          this.FileName= string.Empty;
        }

        /// <summary>
	    /// 账簿编码
	    /// </summary>
        public string AccoutBookNo { get; set; }
        /// <summary>
	    /// 日期
	    /// </summary>
        public System.DateTime? AccountDate { get; set; }
        /// <summary>
	    /// 会计科目
	    /// </summary>
        public string SubjectsCD { get; set; }
        /// <summary>
	    /// 科目明细
	    /// </summary>
        public string SubjectsDetails { get; set; }
        /// <summary>
	    /// 摘要
	    /// </summary>
        public string Abstract { get; set; }
        /// <summary>
	    /// 方向
	    /// </summary>
        public string Direction { get; set; }
        /// <summary>
	    /// 凭证主表ID
	    /// </summary>
        public int? AttestBillID { get; set; }
        /// <summary>
	    /// 凭证明细表ID
	    /// </summary>
        public int? AttestBillDetailsID { get; set; }
        /// <summary>
	    /// 凭证日期
	    /// </summary>
        public System.DateTime? VoucherDate { get; set; }
        /// <summary>
	    /// 币种ID
	    /// </summary>
        public int? CurrencyTypeID { get; set; }
        /// <summary>
	    /// 汇率
	    /// </summary>
        public decimal? ExchangeRate { get; set; }
        /// <summary>
	    /// 外币金额
	    /// </summary>
        public decimal? OriginalAmount { get; set; }
        /// <summary>
	    /// 外币期初余额
	    /// </summary>
        public decimal? ForeignBeginAmount { get; set; }
        /// <summary>
	    /// 外币本期借方金额
	    /// </summary>
        public decimal? ForeignThisDebit { get; set; }
        /// <summary>
	    /// 外币本期贷方金额
	    /// </summary>
        public decimal? ForeignThisCredit { get; set; }
        /// <summary>
	    /// 外币期末余额
	    /// </summary>
        public decimal? ForeignEndAmount { get; set; }
        /// <summary>
	    /// 综合本位币期初余额
	    /// </summary>
        public decimal? BeginAmount { get; set; }
        /// <summary>
	    /// 综合本位币本期借方金额
	    /// </summary>
        public decimal? ThisDebit { get; set; }
        /// <summary>
	    /// 综合本位币本期贷方金额
	    /// </summary>
        public decimal? ThisCredit { get; set; }
        /// <summary>
	    /// 综合本位币期末余额
	    /// </summary>
        public decimal? EndAmount { get; set; }
        /// <summary>
	    /// 公司编码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 凭证号
	    /// </summary>
        public string AttestBillNo { get; set; }
        /// <summary>
	    /// 辅助核算对应表名
	    /// </summary>
        public string FormTBName { get; set; }
        /// <summary>
	    /// 辅助核算对应字段名
	    /// </summary>
        public string FileName { get; set; }

    }
}