//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class AdversaryDynamic : Entity
    {
        public AdversaryDynamic()
        {
          this.CompanyCD= string.Empty;
          this.CustNo= string.Empty;
          this.Dynamic= string.Empty;
          this.InputDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Dynamic { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? InputDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? InputUserID { get; set; }

    }
}