//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class AttendanceEveryDay : Entity
    {
        public AttendanceEveryDay()
        {
          this.EveryDay= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? EveryDay { get; set; }

    }
}