//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class AttestBillDetails : Entity
    {
        public AttestBillDetails()
        {
          this.Abstract= string.Empty;
          this.SubjectsCD= string.Empty;
          this.SubjectsDetails= string.Empty;
          this.FormTBName= string.Empty;
          this.FileName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? AttestBillID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Abstract { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SubjectsCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SubjectsDetails { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? DebitAmount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CreditAmount { get; set; }
        /// <summary>
	    /// 币种ID
	    /// </summary>
        public int? CurrencyTypeID { get; set; }
        /// <summary>
	    /// 外币金额
	    /// </summary>
        public decimal? OriginalAmount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ExchangeRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FormTBName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FileName { get; set; }

    }
}