//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class BackMaterial : Entity
    {
        public BackMaterial()
        {
          this.CompanyCD= string.Empty;
          this.BackNo= string.Empty;
          this.Subject= string.Empty;
          this.FromType= string.Empty;
          this.ReceiveDate= DateTime.Now;
          this.Remark= string.Empty;
          this.CreateDate= DateTime.Now;
          this.BillStatus= string.Empty;
          this.ConfirmDate= DateTime.Now;
          this.CloseDate= DateTime.Now;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BackNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Subject { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? TakeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProcessDeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ManufactureType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SaleID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SaleDeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CountTotal { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Taker { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Receiver { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ReceiveDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Closer { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CloseDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField10 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}