//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class Billing : Entity
    {
        public Billing()
        {
          this.CompanyCD= string.Empty;
          this.BillCD= string.Empty;
          this.BillingNum= string.Empty;
          this.BillingType= string.Empty;
          this.InvoiceType= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ContactUnits= string.Empty;
          this.AcceWay= string.Empty;
          this.AuditDate= DateTime.Now;
          this.IsAccount= string.Empty;
          this.SourceDt= string.Empty;
          this.SourceID= string.Empty;
          this.ColumnName= string.Empty;
          this.AccountsStatus= string.Empty;
          this.Remark= string.Empty;
          this.FromTBName= string.Empty;
          this.FileName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillingNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillingType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InvoiceType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ContactUnits { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AcceWay { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? YAccounts { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? NAccounts { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Executor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Auditor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? AuditDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Register { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SourceDt { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SourceID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ColumnName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccountsStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 币种
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 汇率
	    /// </summary>
        public decimal? CurrencyRate { get; set; }
        /// <summary>
	    /// 往来客户主键
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 往来客户来源表
	    /// </summary>
        public string FromTBName { get; set; }
        /// <summary>
	    /// 往来客户来源表名称字段
	    /// </summary>
        public string FileName { get; set; }

    }
}