//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class Bom : Entity
    {
        public Bom()
        {
          this.CompanyCD= string.Empty;
          this.BomNo= string.Empty;
          this.Subject= string.Empty;
          this.Type= string.Empty;
          this.Verson= string.Empty;
          this.RouteID= 0;
          this.CreateDate= DateTime.Now;
          this.Remark= string.Empty;
          this.ProductID= string.Empty;
          this.UsedStatus= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BomNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Subject { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ParentNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Type { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Verson { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int RouteID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProductID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? UnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? UsedUnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ExRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}