//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CarRepair : Entity
    {
        public CarRepair()
        {
          this.CompanyCD= string.Empty;
          this.CarNo= string.Empty;
          this.EmployeeID= 0;
          this.HappenDate= DateTime.Now;
          this.Factory= string.Empty;
          this.RepairReason= string.Empty;
          this.BillNo= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 车辆编号（对应车辆信息表编号）
	    /// </summary>
        public string CarNo { get; set; }
        /// <summary>
	    /// 经办人
	    /// </summary>
        public int EmployeeID { get; set; }
        /// <summary>
	    /// 维修时间
	    /// </summary>
        public System.DateTime HappenDate { get; set; }
        /// <summary>
	    /// 修理厂
	    /// </summary>
        public string Factory { get; set; }
        /// <summary>
	    /// 维修原因
	    /// </summary>
        public string RepairReason { get; set; }
        /// <summary>
	    /// 维修金额（元）
	    /// </summary>
        public decimal? Fee { get; set; }
        /// <summary>
	    /// 相关发票号
	    /// </summary>
        public string BillNo { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}