//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CheckNotPass : Entity
    {
        public CheckNotPass()
        {
          this.CompanyCD= string.Empty;
          this.ProcessNo= string.Empty;
          this.FromType= string.Empty;
          this.ProcessDate= DateTime.Now;
          this.Remark= string.Empty;
          this.CreateDate= DateTime.Now;
          this.BillStatus= string.Empty;
          this.ConfirmorDate= DateTime.Now;
          this.CloserDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Attachment= string.Empty;
          this.Title= string.Empty;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProcessNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ReportID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Executor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ProcessDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmorDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Closer { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CloserDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 扩展属性1
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 扩展属性2
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 扩展属性3
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 扩展属性4
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 扩展属性5
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 扩展属性6
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 扩展属性7
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 扩展属性8
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 扩展属性9
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 扩展属性10
	    /// </summary>
        public string ExtField10 { get; set; }

    }
}