//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CodeEquipmentType : Entity
    {
        public CodeEquipmentType()
        {
          this.CompanyCD= string.Empty;
          this.TypeFlag= string.Empty;
          this.CodeName= string.Empty;
          this.Description= string.Empty;
          this.Path= string.Empty;
          this.UsedStatus= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 分类标识
	    /// </summary>
        public string TypeFlag { get; set; }
        /// <summary>
	    /// 类别名称
	    /// </summary>
        public string CodeName { get; set; }
        /// <summary>
	    /// 上级类别ID
	    /// </summary>
        public int? SupperID { get; set; }
        /// <summary>
	    /// 描述信息
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 报警下限
	    /// </summary>
        public int? WarningLimit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Path { get; set; }
        /// <summary>
	    /// 启用状态
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}