//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 企业服务开通表
	/// </summary>
    [Table("CompanyOpenServs")]
    public partial class CompanyOpenServ : Entity
    {
        public CompanyOpenServ()
        {
          this.DocSavePath= string.Empty;
          this.OpenDate= string.Empty;
          this.CloseDate= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Remark= string.Empty;
          this.LogoImg= string.Empty;
        }

        /// <summary>
	    /// 最大角色数限制（个数）
	    /// </summary>
        public int? MaxRoles { get; set; }
        /// <summary>
	    /// 最大用户数限制（个数）
	    /// </summary>
        public int? MaxUers { get; set; }
        /// <summary>
	    /// 最大文档存储量（单位：MB）
	    /// </summary>
        public int? MaxDocSize { get; set; }
        /// <summary>
	    /// 单个文档大小限制（单位：MB）
	    /// </summary>
        public int? SingleDocSize { get; set; }
        /// <summary>
	    /// 最大文档数量限制（个数）
	    /// </summary>
        public int? MaxDocNum { get; set; }
        /// <summary>
	    /// 文档存放根目录
	    /// </summary>
        public string DocSavePath { get; set; }
        /// <summary>
	    /// 允许订阅关键字个数
	    /// </summary>
        public int? MaxKeywords { get; set; }
        /// <summary>
	    /// 允许自定义关键字个数
	    /// </summary>
        public int? MaxUserKeywords { get; set; }
        /// <summary>
	    /// 可人工发手机送短信的条数（人工发送短信时减少条数）
	    /// </summary>
        public int? ManMsgNum { get; set; }
        /// <summary>
	    /// 可自动发手机送短信的条数（系统自动发送短信时减少条数）
	    /// </summary>
        public int? AutoMsgNum { get; set; }
        /// <summary>
	    /// 开通服务日期，精确到日yyyymmdd
	    /// </summary>
        public string OpenDate { get; set; }
        /// <summary>
	    /// 结束服务日期，精确到日yyyymmdd
	    /// </summary>
        public string CloseDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogoImg { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public bool? EnableUSBKEYLOGIN { get; set; }

    }
}