//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CostProduction : Entity
    {
        public CostProduction()
        {
          this.CompanyCD= string.Empty;
          this.PeriodNum= string.Empty;
          this.AccountMethod= string.Empty;
          this.IsInvestment= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string PeriodNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccountMethod { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CompRatePro { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsInvestment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? FinishedProductCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? InProuctCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? MaterialsUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? WageUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OverheadUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BurningPowerUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CurrentMonthMaterials { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CurrentMonthHours { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EndMonthHours { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EndMonthMaterials { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CurrencyRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}