//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CustLove : Entity
    {
        public CustLove()
        {
          this.CompanyCD= string.Empty;
          this.LoveNo= string.Empty;
          this.Title= string.Empty;
          this.Contents= string.Empty;
          this.LoveDate= DateTime.Now;
          this.Feedback= string.Empty;
          this.Remarks= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.CanViewUser= string.Empty;
          this.CanViewUserName= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 客户ID
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 客户联系人
	    /// </summary>
        public int? CustLinkMan { get; set; }
        /// <summary>
	    /// 关怀编号
	    /// </summary>
        public string LoveNo { get; set; }
        /// <summary>
	    /// 关怀主题
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 客户关怀分类
	    /// </summary>
        public int? LoveType { get; set; }
        /// <summary>
	    /// 关怀内容
	    /// </summary>
        public string Contents { get; set; }
        /// <summary>
	    /// 执行人
	    /// </summary>
        public int? Linker { get; set; }
        /// <summary>
	    /// 执行日期
	    /// </summary>
        public System.DateTime? LoveDate { get; set; }
        /// <summary>
	    /// 客户反馈
	    /// </summary>
        public string Feedback { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remarks { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUserName { get; set; }

    }
}