//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CustInfo : Entity
    {
        public CustInfo()
        {
          this.CompanyCD= string.Empty;
          this.BigType= string.Empty;
          this.CustNo= string.Empty;
          this.CustName= string.Empty;
          this.CustNam= string.Empty;
          this.CustShort= string.Empty;
          this.CustNote= string.Empty;
          this.Province= string.Empty;
          this.City= string.Empty;
          this.Tel= string.Empty;
          this.Fax= string.Empty;
          this.OnLine= string.Empty;
          this.WebSite= string.Empty;
          this.Post= string.Empty;
          this.HotIs= string.Empty;
          this.HotHow= string.Empty;
          this.MeritGrade= string.Empty;
          this.RelaGrade= string.Empty;
          this.Relation= string.Empty;
          this.CompanyType= string.Empty;
          this.Source= string.Empty;
          this.Phase= string.Empty;
          this.CustSupe= string.Empty;
          this.Trade= string.Empty;
          this.SetupDate= DateTime.Now;
          this.ArtiPerson= string.Empty;
          this.SetupAddress= string.Empty;
          this.TaxCD= string.Empty;
          this.BusiNumber= string.Empty;
          this.IsTax= string.Empty;
          this.SellArea= string.Empty;
          this.SellMode= string.Empty;
          this.ReceiveAddress= string.Empty;
          this.ContactName= string.Empty;
          this.Mobile= string.Empty;
          this.Email= string.Empty;
          this.BusiType= string.Empty;
          this.BillType= string.Empty;
          this.CreditManage= string.Empty;
          this.Remark= string.Empty;
          this.UsedStatus= string.Empty;
          this.CreatedDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.CustTypeManage= string.Empty;
          this.CustTypeSell= string.Empty;
          this.CustTypeTime= string.Empty;
          this.FirstBuyDate= DateTime.Now;
          this.OpenBank= string.Empty;
          this.AccountMan= string.Empty;
          this.AccountNum= string.Empty;
          this.CanViewUser= string.Empty;
          this.CanViewUserName= string.Empty;
          this.CompanyValues= string.Empty;
          this.CatchWord= string.Empty;
          this.ManageValues= string.Empty;
          this.Potential= string.Empty;
          this.Problem= string.Empty;
          this.Advantages= string.Empty;
          this.TradePosition= string.Empty;
          this.Competition= string.Empty;
          this.Collaborator= string.Empty;
          this.ManagePlan= string.Empty;
          this.Collaborate= string.Empty;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
          this.ExtField11= string.Empty;
          this.ExtField12= string.Empty;
          this.ExtField13= string.Empty;
          this.ExtField14= string.Empty;
          this.ExtField15= string.Empty;
          this.ExtField16= string.Empty;
          this.ExtField17= string.Empty;
          this.ExtField18= string.Empty;
          this.ExtField19= string.Empty;
          this.ExtField20= string.Empty;
          this.ExtField21= string.Empty;
          this.ExtField22= string.Empty;
          this.ExtField23= string.Empty;
          this.ExtField24= string.Empty;
          this.ExtField25= string.Empty;
          this.ExtField26= string.Empty;
          this.ExtField27= string.Empty;
          this.ExtField28= string.Empty;
          this.ExtField29= string.Empty;
          this.ExtField30= string.Empty;
          this.CustBig= string.Empty;
          this.CustNum= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BigType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustClass { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustNam { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustShort { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CreditGrade { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustNote { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Manager { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AreaID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CountryID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Province { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string City { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Tel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Fax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OnLine { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string WebSite { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Post { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? LinkCycle { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string HotIs { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string HotHow { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string MeritGrade { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string RelaGrade { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Relation { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? StaffCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Source { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Phase { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustSupe { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Trade { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? SetupDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ArtiPerson { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SetupMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SetupAddress { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CapitalScale { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SaleroomY { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ProfitY { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string TaxCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BusiNumber { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SellArea { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SellMode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ReceiveAddress { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ContactName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Mobile { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Email { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? TakeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CarryType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BusiType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? PayType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreditManage { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? MaxCredit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreatedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? MoneyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustTypeManage { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustTypeSell { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustTypeTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? FirstBuyDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? MaxCreditDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OpenBank { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccountMan { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccountNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyValues { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CatchWord { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ManageValues { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Potential { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Problem { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Advantages { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string TradePosition { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Competition { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Collaborator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ManagePlan { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Collaborate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField10 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField11 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField12 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField13 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField14 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField15 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField16 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField17 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField18 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField19 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField20 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField21 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField22 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField23 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField24 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField25 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField26 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField27 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField28 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField29 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField30 { get; set; }
        /// <summary>
	    /// 客户大类
	    /// </summary>
        public string CustBig { get; set; }
        /// <summary>
	    /// 卡号
	    /// </summary>
        public string CustNum { get; set; }

        public virtual CustInfo CustInfoMember { get; set; }
        public virtual CustInfo CustInfoMember1 { get; set; }
    }
}