//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CustService : Entity
    {
        public CustService()
        {
          this.CompanyCD= string.Empty;
          this.ServeNO= string.Empty;
          this.CustLinkTel= string.Empty;
          this.Title= string.Empty;
          this.State= string.Empty;
          this.BeginDate= DateTime.Now;
          this.DateUnit= string.Empty;
          this.Contents= string.Empty;
          this.Feedback= string.Empty;
          this.LinkQA= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.CanViewUser= string.Empty;
          this.CanViewUserName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ServeNO { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustLinkMan { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustLinkTel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ServeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Fashion { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string State { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? BeginDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DateUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SpendTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? OurLinkMan { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Executant { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Contents { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Feedback { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LinkQA { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUserName { get; set; }

    }
}