//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CustomTable : Entity
    {
        public CustomTable()
        {
          this.CompanyCD= string.Empty;
          this.CustomTableName= string.Empty;
          this.AliasTableName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustomTableName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AliasTableName { get; set; }
        /// <summary>
	    /// 1:正常;2:已经成功生产物理表
	    /// </summary>
        public int? Status { get; set; }
        /// <summary>
	    /// 0:不是字典表  1:是字典表
	    /// </summary>
        public int? IsDic { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ParentId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ColumnNumber { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? TotalFlag { get; set; }

    }
}