//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class CustCall : Entity
    {
        public CustCall()
        {
          this.CompanyCD= string.Empty;
          this.Tel= string.Empty;
          this.Callor= string.Empty;
          this.CallTime= DateTime.Now;
          this.CallContents= string.Empty;
          this.Title= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 客户ID
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 来电号码
	    /// </summary>
        public string Tel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Callor { get; set; }
        /// <summary>
	    /// 来电时间
	    /// </summary>
        public System.DateTime? CallTime { get; set; }
        /// <summary>
	    /// 来电内容
	    /// </summary>
        public string CallContents { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}