//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
    /// 
    /// </summary>
    [Table("DeptQuarter")]
    public partial class DeptQuarter : Entity
    {
        public DeptQuarter()
        {
          this.CompanyCD= string.Empty;
          this.DeptID= 0;
          this.QuarterNo= string.Empty;
          this.PYShort= string.Empty;
          this.QuarterName= string.Empty;
          this.KeyFlag= string.Empty;
          this.Duty= string.Empty;
          this.UsedStatus= string.Empty;
          this.Description= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.DutyRequire= string.Empty;
          this.Attachment= string.Empty;
          this.QuterContent= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 部门ID（对应部门表ID）
	    /// </summary>
        public int DeptID { get; set; }
        /// <summary>
	    /// 岗位编号
	    /// </summary>
        public string QuarterNo { get; set; }
        /// <summary>
	    /// 上级岗位ID
	    /// </summary>
        public int? SuperQuarterID { get; set; }
        /// <summary>
	    /// 岗位拼音代码
	    /// </summary>
        public string PYShort { get; set; }
        /// <summary>
	    /// 岗位名称
	    /// </summary>
        public string QuarterName { get; set; }
        /// <summary>
	    /// 岗位类型ID（对应分类代码表ID）
	    /// </summary>
        public int? TypeID { get; set; }
        /// <summary>
	    /// 岗位级别ID（对应分类代码表ID）
	    /// </summary>
        public int? LevelID { get; set; }
        /// <summary>
	    /// 是否关键岗位(0 否，1 是)
	    /// </summary>
        public string KeyFlag { get; set; }
        /// <summary>
	    /// 岗位职责
	    /// </summary>
        public string Duty { get; set; }
        /// <summary>
	    /// 启用状态(0 停用，1 启用)
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 描述
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DutyRequire { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachment { get; set; }
        /// <summary>
	    /// 岗位说明书内容
	    /// </summary>
        public string QuterContent { get; set; }

    }
}