//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class DocInfo : Entity
    {
        public DocInfo()
        {
          this.CompanyCD= string.Empty;
          this.DocumentNo= string.Empty;
          this.DocTitle= string.Empty;
          this.UploadDate= DateTime.Now;
          this.DocumentName= string.Empty;
          this.DocumentURL= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 文档编号
	    /// </summary>
        public string DocumentNo { get; set; }
        /// <summary>
	    /// 文档分类ID
	    /// </summary>
        public int? DocType { get; set; }
        /// <summary>
	    /// 文档说明
	    /// </summary>
        public string DocTitle { get; set; }
        /// <summary>
	    /// 上传人ID
	    /// </summary>
        public int? UploadUserID { get; set; }
        /// <summary>
	    /// 所属部门ID
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 上传时间
	    /// </summary>
        public System.DateTime? UploadDate { get; set; }
        /// <summary>
	    /// 文档名称
	    /// </summary>
        public string DocumentName { get; set; }
        /// <summary>
	    /// 文档URL
	    /// </summary>
        public string DocumentURL { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}