//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EmployeeInfoTemp : Entity
    {
        public EmployeeInfoTemp()
        {
          this.Ncode= 0;
          this.企业编号= string.Empty;
          this.身份证= string.Empty;
          this.姓名= string.Empty;
          this.性别= string.Empty;
          this.生日= string.Empty;
          this.目前所在岗位= string.Empty;
          this.岗位编号= string.Empty;
          this.目前所在部门= string.Empty;
          this.部门编号= string.Empty;
          this.入职时间= string.Empty;
          this.婚姻状况= string.Empty;
          this.联系电话= string.Empty;
          this.手机号码= string.Empty;
          this.家庭住址= string.Empty;
          this.参加工作时间= string.Empty;
          this.人员分类= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int Ncode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? 流水号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 企业编号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 身份证 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 姓名 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 性别 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 生日 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 目前所在岗位 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 岗位编号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 目前所在部门 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 部门编号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 入职时间 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 婚姻状况 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 联系电话 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 手机号码 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 家庭住址 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 参加工作时间 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 人员分类 { get; set; }

    }
}