//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 员工信息表
	/// </summary>
    [Table("EmployeeInfo")]
    public partial class EmployeeInfo: Entity
    {
        public EmployeeInfo()
        {
          this.EmployeeNo= string.Empty;
          this.EmployeeNum= string.Empty;
          this.PYShort= string.Empty;
          this.CompanyCD= string.Empty;
          this.CardID= string.Empty;
          this.SafeguardCard= string.Empty;
          this.EmployeeName= string.Empty;
          this.UsedName= string.Empty;
          this.NameEn= string.Empty;
          this.Sex= string.Empty;
          this.Birth= DateTime.Now;
          this.Account= string.Empty;
          this.AccountNature= string.Empty;
          this.Degree= string.Empty;
          this.DocuType= string.Empty;
          this.Origin= string.Empty;
          this.Telephone= string.Empty;
          this.Mobile= string.Empty;
          this.EMail= string.Empty;
          this.OtherContact= string.Empty;
          this.HomeAddress= string.Empty;
          this.HealthStatus= string.Empty;
          this.GraduateSchool= string.Empty;
          this.Features= string.Empty;
          this.ComputerLevel= string.Empty;
          this.ForeignLanguageLevel1= string.Empty;
          this.ForeignLanguageLevel2= string.Empty;
          this.ForeignLanguageLevel3= string.Empty;
          this.WorkTime= DateTime.Now;
          this.PhotoURL= string.Empty;
          this.PositionTitle= string.Empty;
          this.Flag= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Resume= string.Empty;
          this.EnterDate= DateTime.Now;
          this.Attachmentname= string.Empty;
          this.ProfessionalDes= string.Empty;
          this.DelFlag= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string EmployeeNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string EmployeeNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string PYShort { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CardID { get; set; }
        /// <summary>
	    /// 社保卡号
	    /// </summary>
        public string SafeguardCard { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string EmployeeName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string NameEn { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Sex { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? Birth { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Account { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccountNature { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CountryID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Height { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Weight { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Sight { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Degree { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? PositionID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string QuarterID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DocuType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? NationalID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? MarriageStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Origin { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Landscape { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Religion { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Telephone { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Mobile { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string EMail { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OtherContact { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string HomeAddress { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string HealthStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CultureLevel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string GraduateSchool { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Professional { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Features { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ComputerLevel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ForeignLanguage1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ForeignLanguageLevel1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ForeignLanguage2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ForeignLanguageLevel2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ForeignLanguage3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ForeignLanguageLevel3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? WorkTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalSeniority { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string PhotoURL { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string PositionTitle { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Flag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Resume { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AdminLevelID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? EnterDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachmentname { get; set; }
        /// <summary>
	    /// 专业描述
	    /// </summary>
        public string ProfessionalDes { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DelFlag { get; set; }

    }
}