//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EmployeeAttendanceSet : Entity
    {
        public EmployeeAttendanceSet()
        {
          this.CompanyCD= string.Empty;
          this.EmployeeID= 0;
          this.WorkGroupNo= string.Empty;
          this.AttendanceType= string.Empty;
          this.WorkOverTimeType= string.Empty;
          this.WeekRestDay= string.Empty;
          this.MonthRestDay= string.Empty;
          this.StartDate= DateTime.Now;
          this.EndDate= DateTime.Now;
          this.ModifiledDate= DateTime.Now;
          this.ModifiledUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 员工ID
	    /// </summary>
        public int EmployeeID { get; set; }
        /// <summary>
	    /// 班组编号
	    /// </summary>
        public string WorkGroupNo { get; set; }
        /// <summary>
	    /// 考勤类型(正常考勤、免签、不处理)
	    /// </summary>
        public string AttendanceType { get; set; }
        /// <summary>
	    /// 加班类型(自动计算加班、不计算加班、只计算节假日加班)
	    /// </summary>
        public string WorkOverTimeType { get; set; }
        /// <summary>
	    /// 每周休息日
	    /// </summary>
        public string WeekRestDay { get; set; }
        /// <summary>
	    /// 每月休息日
	    /// </summary>
        public string MonthRestDay { get; set; }
        /// <summary>
	    /// 开始日期
	    /// </summary>
        public System.DateTime? StartDate { get; set; }
        /// <summary>
	    /// 结束日期
	    /// </summary>
        public System.DateTime? EndDate { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiledDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiledUserID { get; set; }

    }
}