//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EmployeeHistory : Entity
    {
        public EmployeeHistory()
        {
          this.CompanyCD= string.Empty;
          this.EmployeeNo= string.Empty;
          this.StartDate= DateTime.Now;
          this.EndDate= DateTime.Now;
          this.Flag= string.Empty;
          this.Company= string.Empty;
          this.Department= string.Empty;
          this.WorkContent= string.Empty;
          this.LeaveReason= string.Empty;
          this.SchoolName= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string EmployeeNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? StartDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? EndDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Flag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Company { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Department { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string WorkContent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LeaveReason { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchoolName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Professional { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CultureLevel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}