//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EndItemProcSetting : Entity
    {
        public EndItemProcSetting()
        {
          this.CompanyCD= string.Empty;
          this.ItemName= string.Empty;
          this.UsedStatus= string.Empty;
            ItemEndItemProcessedRecords = new List<EndItemProcessedRecord>();
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ItemName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ShowIndex { get; set; }

        public virtual ICollection<EndItemProcessedRecord> ItemEndItemProcessedRecords { get; set; }
    }
}