//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EquipmentRepair : Entity
    {
        public EquipmentRepair()
        {
          this.RecordNo= string.Empty;
          this.CompanyCD= string.Empty;
          this.EquipmentNo= string.Empty;
          this.ReportUserID= 0;
          this.DeptID= 0;
          this.Trouble= string.Empty;
          this.Date= DateTime.Now;
          this.TroubleLevel= string.Empty;
          this.HopeRepairDate= DateTime.Now;
          this.RepairType= string.Empty;
          this.ToRepairDate= DateTime.Now;
          this.PlanDate= DateTime.Now;
          this.SolveDate= DateTime.Now;
          this.RepairUser= string.Empty;
          this.RepairParts= string.Empty;
          this.PartsCheck= string.Empty;
          this.Remark= string.Empty;
          this.TroubleStatus= string.Empty;
          this.CompleteDate= DateTime.Now;
          this.TroubleDescription= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.CreateDate= DateTime.Now;
        }

        /// <summary>
	    /// 单据编号
	    /// </summary>
        public string RecordNo { get; set; }
        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 设备编号
	    /// </summary>
        public string EquipmentNo { get; set; }
        /// <summary>
	    /// 报修人ID
	    /// </summary>
        public int ReportUserID { get; set; }
        /// <summary>
	    /// 报修人部门ID
	    /// </summary>
        public int DeptID { get; set; }
        /// <summary>
	    /// 故障症状
	    /// </summary>
        public string Trouble { get; set; }
        /// <summary>
	    /// 发生时间
	    /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
	    /// 故障程度
	    /// </summary>
        public string TroubleLevel { get; set; }
        /// <summary>
	    /// 希望修复时间
	    /// </summary>
        public System.DateTime? HopeRepairDate { get; set; }
        /// <summary>
	    /// 修理方式
	    /// </summary>
        public string RepairType { get; set; }
        /// <summary>
	    /// 送修（自修）时间
	    /// </summary>
        public System.DateTime? ToRepairDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? PlanDate { get; set; }
        /// <summary>
	    /// 实际修复时间
	    /// </summary>
        public System.DateTime? SolveDate { get; set; }
        /// <summary>
	    /// 修理人员
	    /// </summary>
        public string RepairUser { get; set; }
        /// <summary>
	    /// 修理工时
	    /// </summary>
        public decimal? RepairHours { get; set; }
        /// <summary>
	    /// 更换零件
	    /// </summary>
        public string RepairParts { get; set; }
        /// <summary>
	    /// 更换零件验收
	    /// </summary>
        public string PartsCheck { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 故障状态
	    /// </summary>
        public string TroubleStatus { get; set; }
        /// <summary>
	    /// 预计维修费用
	    /// </summary>
        public decimal? PlanCost { get; set; }
        /// <summary>
	    /// 完成日期
	    /// </summary>
        public System.DateTime? CompleteDate { get; set; }
        /// <summary>
	    /// 实际维修费用
	    /// </summary>
        public decimal? FactCost { get; set; }
        /// <summary>
	    /// 故障及维护描述
	    /// </summary>
        public string TroubleDescription { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 制单人
	    /// </summary>
        public int? CreateUser { get; set; }
        /// <summary>
	    /// 制单日期
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }

    }
}