//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ExportLog : Entity
    {
        public ExportLog()
        {
          this.Id= 0;
          this.CompanyCD= string.Empty;
          this.ExportEmpID= string.Empty;
          this.ExportDate= DateTime.Now;
          this.ExportObject= string.Empty;
          this.ExportError= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExportEmpID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ExportDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExportObject { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ExportNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ExportResult { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExportError { get; set; }

    }
}