//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FeeApplyDetail : Entity
    {
        public FeeApplyDetail()
        {
          this.ExpRemark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? ExpID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SortNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ExpType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Amount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExpRemark { get; set; }

    }
}