//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FeeReturn : Entity
    {
        public FeeReturn()
        {
          this.CompanyCD= string.Empty;
          this.ReimbNo= string.Empty;
          this.Title= string.Empty;
          this.ReimbDate= DateTime.Now;
          this.Status= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ConfirmDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.Remark= string.Empty;
          this.FromType= string.Empty;
          this.CanViewUser= string.Empty;
          this.IsFeesAccount= string.Empty;
          this.SubjectsNo= string.Empty;
          this.IsAccount= string.Empty;
          this.AccountDate= DateTime.Now;
          this.FromTBName= string.Empty;
          this.ContactsUnitName= string.Empty;
          this.Attachment= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ReimbNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Applyor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ReimbDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ExpAllAmount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ReimbAllAmount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? RestoreAllAmount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ReimbDeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? UserReimbID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsFeesAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProjectID { get; set; }
        /// <summary>
	    /// 结算科目
	    /// </summary>
        public string SubjectsNo { get; set; }
        /// <summary>
	    /// 是否登记凭证
	    /// </summary>
        public string IsAccount { get; set; }
        /// <summary>
	    /// 登记时间
	    /// </summary>
        public System.DateTime? AccountDate { get; set; }
        /// <summary>
	    /// 登记凭证人
	    /// </summary>
        public int? Accountor { get; set; }
        /// <summary>
	    /// 生成凭证ID
	    /// </summary>
        public int? AttestBillID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ContactsUnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromTBName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ContactsUnitName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachment { get; set; }

    }
}