//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FixAssetInfo : Entity
    {
        public FixAssetInfo()
        {
          this.CompanyCD= string.Empty;
          this.FixNo= string.Empty;
          this.FixName= string.Empty;
          this.FixSpec= string.Empty;
          this.FixModel= string.Empty;
          this.Unit= string.Empty;
          this.UseDept= string.Empty;
          this.StorePlace= string.Empty;
          this.RespPerson= string.Empty;
          this.RegisterDate= DateTime.Now;
          this.UsedStatus= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FixType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixSpec { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixModel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FixNumber { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Unit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OriginalValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UseDept { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string StorePlace { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string RespPerson { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? RegisterDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BegiDisCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ReduValueRe { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? NetValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}