//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FixAssetDeprDetail : Entity
    {
        public FixAssetDeprDetail()
        {
          this.CompanyCD= string.Empty;
          this.FixNo= string.Empty;
          this.FixName= string.Empty;
          this.UsedDate= DateTime.Now;
          this.DeprDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FixType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? UsedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? DeprDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Number { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? UsedYears { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EstimateUse { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OriginalValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? MDeprPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalDeprPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EndNetValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalImpairment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }

    }
}