//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FixWithInfo : Entity
    {
        public FixWithInfo()
        {
          this.CompanyCD= string.Empty;
          this.FixNo= string.Empty;
          this.UseDate= DateTime.Now;
          this.CountMethod= string.Empty;
          this.AccuDeprSubjeCD= string.Empty;
          this.DeprCostSubjeCD= string.Empty;
          this.DeprStatus= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FixNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? UseDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CountMethod { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EstimateUse { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? UsedYear { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? EstiResiValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AccuDeprSubjeCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DeprCostSubjeCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? EstiWorkLoad { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? AmorDeprRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? AmorDeprM { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CurrValueRe { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DeprStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? EndNetValue { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? MonthWorkLoad { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalDeprPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}