//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FlowTaskHistory : Entity
    {
        public FlowTaskHistory()
        {
          this.CompanyCD= string.Empty;
          this.FlowInstanceID= 0;
          this.FlowNo= string.Empty;
          this.BillID= string.Empty;
          this.StepNo= 0;
          this.State= string.Empty;
          this.OperateUserId= string.Empty;
          this.OperateDate= DateTime.Now;
          this.Note= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int FlowInstanceID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FlowNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? BillTypeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int StepNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string State { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OperateUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? OperateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Note { get; set; }

    }
}