//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class FormulaDetails : Entity
    {
        public FormulaDetails()
        {
          this.SubjectsCD= string.Empty;
          this.SubjectsName= string.Empty;
          this.Direction= string.Empty;
          this.Operator= string.Empty;
          this.CompanyCD= string.Empty;
        }

        /// <summary>
	    /// 资产负债表项目ID
	    /// </summary>
        public int? FormulaID { get; set; }
        /// <summary>
	    /// 科目编码
	    /// </summary>
        public string SubjectsCD { get; set; }
        /// <summary>
	    /// 科目名称
	    /// </summary>
        public string SubjectsName { get; set; }
        /// <summary>
	    /// 方向
	    /// </summary>
        public string Direction { get; set; }
        /// <summary>
	    /// 运算符
	    /// </summary>
        public string Operator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }

    }
}