//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class InputDepatmentRoyalty : Entity
    {
        public InputDepatmentRoyalty()
        {
          this.DeptID= 0;
          this.CompanyCD= string.Empty;
          this.ModifiedUserID= string.Empty;
          this.CreateTime= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BusinessMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? RatePercent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }

    }
}