//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class InputPersonalRoyalty : Entity
    {
        public InputPersonalRoyalty()
        {
          this.EmployeeID= 0;
          this.CompanyCD= string.Empty;
          this.FromType= string.Empty;
          this.FromBillNo= string.Empty;
          this.ModifiedUserID= string.Empty;
          this.CreateTime= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int EmployeeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Rate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? AfterTaxMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? NewCustomerTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromBillNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }

    }
}