//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class InSideChangeAcco : Entity
    {
        public InSideChangeAcco()
        {
          this.CompanyCD= string.Empty;
          this.ChangeNo= string.Empty;
          this.ChangeBillNum= string.Empty;
          this.ChangeDate= DateTime.Now;
          this.InAccountNo= string.Empty;
          this.InBankName= string.Empty;
          this.OutAccountNo= string.Empty;
          this.OutBankName= string.Empty;
          this.Summary= string.Empty;
          this.ConfirmStatus= string.Empty;
          this.ConfirmDate= DateTime.Now;
          this.IsAccount= string.Empty;
          this.AccountDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ChangeNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ChangeBillNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ChangeDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InAccountNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InBankName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OutAccountNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OutBankName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Executor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Summary { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ConfirmStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Accountor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? AccountDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ModifiedUserID { get; set; }
        /// <summary>
	    /// 生成凭证ID
	    /// </summary>
        public int? AttestBillID { get; set; }
        /// <summary>
	    /// 币种
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 汇率
	    /// </summary>
        public decimal? CurrencyRate { get; set; }

    }
}