//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class KnowledgeRequire : Entity
    {
        public KnowledgeRequire()
        {
          this.CompanyCD= string.Empty;
          this.SendDate= DateTime.Now;
          this.SendUserID= string.Empty;
          this.Content= string.Empty;
          this.FeeBackStatus= string.Empty;
          this.FeeBackDate= DateTime.Now;
          this.FeeBackUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime SendDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SendUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Content { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FeeBackStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? FeeBackDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FeeBackUserID { get; set; }

    }
}