//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class MasterProductScheduleDetail : Entity
    {
        public MasterProductScheduleDetail()
        {
          this.CompanyCD= string.Empty;
          this.PlanNo= string.Empty;
          this.Specification= string.Empty;
          this.StartDate= DateTime.Now;
          this.EndDate= DateTime.Now;
          this.FromBillNo= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司编码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 主生产计划编号（对应主生产计划表）
	    /// </summary>
        public string PlanNo { get; set; }
        /// <summary>
	    /// 序号（行号）
	    /// </summary>
        public int? SortNo { get; set; }
        /// <summary>
	    /// 物品ID
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 单位
	    /// </summary>
        public int? UsedUnitID { get; set; }
        /// <summary>
	    /// 数量
	    /// </summary>
        public decimal? UsedUnitCount { get; set; }
        /// <summary>
	    /// 单位换算率
	    /// </summary>
        public decimal? ExRate { get; set; }
        /// <summary>
	    /// 基本单位
	    /// </summary>
        public int? UnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Specification { get; set; }
        /// <summary>
	    /// 计划需求数量
	    /// </summary>
        public decimal? ProductCount { get; set; }
        /// <summary>
	    /// 计划生产数量
	    /// </summary>
        public decimal? ProduceCount { get; set; }
        /// <summary>
	    /// 计划开始时间
	    /// </summary>
        public System.DateTime? StartDate { get; set; }
        /// <summary>
	    /// 计划完成时间
	    /// </summary>
        public System.DateTime? EndDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromBillNo { get; set; }
        /// <summary>
	    /// 来源销售订单ID（对应销售订单表ID）
	    /// </summary>
        public int? FromBillID { get; set; }
        /// <summary>
	    /// 来源销售订单行号
	    /// </summary>
        public int? FromLineNo { get; set; }
        /// <summary>
	    /// 已下达数量（由生产任务单更新）
	    /// </summary>
        public decimal? PlanCount { get; set; }
        /// <summary>
	    /// 已生产数量（由生产任务单更新）
	    /// </summary>
        public decimal? ProcessedCount { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID（对应操作用户表的UserID）
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}