//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class MeetingDecision : Entity
    {
        public MeetingDecision()
        {
          this.Id= 0;
          this.CompanyCD= string.Empty;
          this.RecordNo= string.Empty;
          this.DecisionNo= string.Empty;
          this.Contents= string.Empty;
          this.Aim= string.Empty;
          this.CompleteDate= DateTime.Now;
          this.Status= string.Empty;
          this.CheckDate= DateTime.Now;
          this.CheckResult= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 会议记录编号（对应会议记录编号）
	    /// </summary>
        public string RecordNo { get; set; }
        /// <summary>
	    /// 会议决议编号
	    /// </summary>
        public string DecisionNo { get; set; }
        /// <summary>
	    /// 决议事项
	    /// </summary>
        public string Contents { get; set; }
        /// <summary>
	    /// 执行负责人
	    /// </summary>
        public int? Principal { get; set; }
        /// <summary>
	    /// 实施目标
	    /// </summary>
        public string Aim { get; set; }
        /// <summary>
	    /// 完成期限
	    /// </summary>
        public System.DateTime? CompleteDate { get; set; }
        /// <summary>
	    /// 完成状态（1未完成，2已完成）
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 检查人
	    /// </summary>
        public int? Cheker { get; set; }
        /// <summary>
	    /// 核查时间
	    /// </summary>
        public System.DateTime? CheckDate { get; set; }
        /// <summary>
	    /// 核查结果
	    /// </summary>
        public string CheckResult { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}