//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class MeetingTalk : Entity
    {
        public MeetingTalk()
        {
          this.CompanyCD= string.Empty;
          this.RecordNo= string.Empty;
          this.Topic= string.Empty;
          this.Contents= string.Empty;
          this.Important= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 会议记录编号（对应会议记录编号）
	    /// </summary>
        public string RecordNo { get; set; }
        /// <summary>
	    /// 发言人
	    /// </summary>
        public int? Talker { get; set; }
        /// <summary>
	    /// 主旨
	    /// </summary>
        public string Topic { get; set; }
        /// <summary>
	    /// 发言要点
	    /// </summary>
        public string Contents { get; set; }
        /// <summary>
	    /// 重要程度(1不重要,2普通,3重要,4关键)
	    /// </summary>
        public string Important { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }

    }
}