//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class MoveApply : Entity
    {
        public MoveApply()
        {
          this.CompanyCD= string.Empty;
          this.MoveApplyNo= string.Empty;
          this.EmployeeID= 0;
          this.EnterDate= DateTime.Now;
          this.ApplyDate= DateTime.Now;
          this.HopeDate= DateTime.Now;
          this.ContractValid= DateTime.Now;
          this.MoveDate= DateTime.Now;
          this.MoveType= string.Empty;
          this.Interview= string.Empty;
          this.Reason= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Title= string.Empty;
          this.Status= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string MoveApplyNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int EmployeeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? EnterDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ApplyDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? HopeDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? QuarterID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ContractValid { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? MoveDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string MoveType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Interview { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Reason { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Status { get; set; }

    }
}