//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class MyCollector : Entity
    {
        public MyCollector()
        {
          this.Flag= string.Empty;
          this.InfoID= 0;
          this.Owner= string.Empty;
          this.SourceType= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ReadStatus= string.Empty;
          this.ReadDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? RootID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Flag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int InfoID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Owner { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SourceType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ReadStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ReadDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}