//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class OperatingRecord : Entity
    {
        public OperatingRecord()
        {
          this.DTName= string.Empty;
          this.DtOt= string.Empty;
          this.CreateDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string DTName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid? DTRKey { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DtOt { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }

    }
}