//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PerformanceElem : Entity
    {
        public PerformanceElem()
        {
          this.CompanyCD= string.Empty;
          this.ElemNo= string.Empty;
          this.ElemName= string.Empty;
          this.ScoreRules= string.Empty;
          this.AsseStandard= string.Empty;
          this.AsseFrom= string.Empty;
          this.Remark= string.Empty;
          this.UsedStatus= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 指标编号
	    /// </summary>
        public string ElemNo { get; set; }
        /// <summary>
	    /// 指标名称
	    /// </summary>
        public string ElemName { get; set; }
        /// <summary>
	    /// 父指标编号
	    /// </summary>
        public int? ParentElemNo { get; set; }
        /// <summary>
	    /// 评分细则
	    /// </summary>
        public string ScoreRules { get; set; }
        /// <summary>
	    /// 标准分
	    /// </summary>
        public int? StandardScore { get; set; }
        /// <summary>
	    /// 评分最小值
	    /// </summary>
        public int? MinScore { get; set; }
        /// <summary>
	    /// 评分最大值 
	    /// </summary>
        public int? MaxScore { get; set; }
        /// <summary>
	    /// 评分标准
	    /// </summary>
        public string AsseStandard { get; set; }
        /// <summary>
	    /// 评分来源(如业绩)
	    /// </summary>
        public string AsseFrom { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 启用状态
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}