//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PerformanceSummary : Entity
    {
        public PerformanceSummary()
        {
          this.CompanyCD= string.Empty;
          this.TaskNo= string.Empty;
          this.TemplateNo= string.Empty;
          this.RewardNote= string.Empty;
          this.SummaryNote= string.Empty;
          this.LevelType= string.Empty;
          this.AdviceType= string.Empty;
          this.AdviceNote= string.Empty;
          this.Remark= string.Empty;
          this.EvaluateDate= DateTime.Now;
          this.SignDate= DateTime.Now;
          this.SignNote= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 考核任务编号
	    /// </summary>
        public string TaskNo { get; set; }
        /// <summary>
	    /// 模板编号
	    /// </summary>
        public string TemplateNo { get; set; }
        /// <summary>
	    /// 被考核人（对应员工表ID）
	    /// </summary>
        public int? EmployeeID { get; set; }
        /// <summary>
	    /// 考核总得分
	    /// </summary>
        public int? TotalScore { get; set; }
        /// <summary>
	    /// 奖惩说明
	    /// </summary>
        public string RewardNote { get; set; }
        /// <summary>
	    /// 累计扣分
	    /// </summary>
        public int? KillScore { get; set; }
        /// <summary>
	    /// 累计加分
	    /// </summary>
        public int? AddScore { get; set; }
        /// <summary>
	    /// 实际得分
	    /// </summary>
        public int? RealScore { get; set; }
        /// <summary>
	    /// 总评
	    /// </summary>
        public string SummaryNote { get; set; }
        /// <summary>
	    /// 考核等级（1达到要求，2超过要求，3表现突出，4需要改进，5不合格）
	    /// </summary>
        public string LevelType { get; set; }
        /// <summary>
	    /// 考核建议（1不做处理，2调整薪资，3晋升，4调职，5辅导，6培训，7辞退）
	    /// </summary>
        public string AdviceType { get; set; }
        /// <summary>
	    /// 建议说明
	    /// </summary>
        public string AdviceNote { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 总评人
	    /// </summary>
        public int? Evaluater { get; set; }
        /// <summary>
	    /// 总评日期
	    /// </summary>
        public System.DateTime? EvaluateDate { get; set; }
        /// <summary>
	    /// 被考核人确认时间
	    /// </summary>
        public System.DateTime? SignDate { get; set; }
        /// <summary>
	    /// 被考核人反馈
	    /// </summary>
        public string SignNote { get; set; }
        /// <summary>
	    /// 更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}