//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PersonalScratchpad : Entity
    {
        public PersonalScratchpad()
        {
          this.CompanyCD= string.Empty;
          this.Title= string.Empty;
          this.Content= string.Empty;
          this.RecordsDate= DateTime.Now;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Owner { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Content { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? RecordsDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}