//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PlanCheck : Entity
    {
        public PlanCheck()
        {
          this.CompanyCD= string.Empty;
          this.CheckDate= DateTime.Now;
          this.CheckMethod= string.Empty;
          this.CheckContent= string.Empty;
          this.CheckResult= string.Empty;
          this.AddOrCut= string.Empty;
          this.Remark= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AimID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CheckDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Checkor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CheckMethod { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CheckContent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CheckResult { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AddOrCut { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}