//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PlanAim : Entity
    {
        public PlanAim()
        {
          this.CompanyCD= string.Empty;
          this.AimNo= string.Empty;
          this.AimTitle= string.Empty;
          this.AimContent= string.Empty;
          this.AimStandard= string.Empty;
          this.AimStep= string.Empty;
          this.Resources= string.Empty;
          this.Qustion= string.Empty;
          this.Method= string.Empty;
          this.AimFlag= string.Empty;
          this.JoinUserIDList= string.Empty;
          this.JoinUserNameList= string.Empty;
          this.Attachment= string.Empty;
          this.Memo= string.Empty;
          this.Critical= string.Empty;
          this.Important= string.Empty;
          this.Priority= string.Empty;
          this.AttentionName= string.Empty;
          this.Status= string.Empty;
          this.Remark= string.Empty;
          this.CreateDate= DateTime.Now;
          this.SummarizeDate= DateTime.Now;
          this.SummarizeNote= string.Empty;
          this.AimRealResult= string.Empty;
          this.AddOrCut= string.Empty;
          this.Difference= string.Empty;
          this.ScoreNote= string.Empty;
          this.CheckNote= string.Empty;
          this.CheckDate= DateTime.Now;
          this.StartDate= DateTime.Now;
          this.EndDate= DateTime.Now;
          this.ConfirmDate= DateTime.Now;
          this.CancelDate= DateTime.Now;
          this.CancelReson= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.AimDate= string.Empty;
          this.CanViewUser= string.Empty;
          this.CanViewUserName= string.Empty;
          this.IsMobileNotice= string.Empty;
          this.RemindTime= DateTime.Now;
          this.IsDirection= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AimTypeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimTitle { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimContent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimStandard { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimStep { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Resources { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Qustion { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Method { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string JoinUserIDList { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string JoinUserNameList { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? PrincipalID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Memo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Critical { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Important { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Priority { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AttentionName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Coordinator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? SummarizeDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SummarizeNote { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Summarizer { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimRealResult { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AddOrCut { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Difference { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CompletePercent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CheckScore { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ScoreNote { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CheckUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CheckNote { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CheckDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? StartDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? EndDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Canceler { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CancelDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CancelReson { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AimNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AimDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsMobileNotice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? RemindTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsDirection { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Checkor { get; set; }

    }
}