//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PrintParameterSetting : Entity
    {
        public PrintParameterSetting()
        {
          this.CompanyCD= string.Empty;
          this.BaseFields= string.Empty;
          this.DetailFields= string.Empty;
          this.DetailSecondFields= string.Empty;
          this.DetailThreeFields= string.Empty;
          this.DetailFourFields= string.Empty;
          this.ModifiedDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? BillTypeFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? PrintTypeFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BaseFields { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DetailFields { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DetailSecondFields { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DetailThreeFields { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DetailFourFields { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }

    }
}