//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ProcessLog : Entity
    {
        public ProcessLog()
        {
          this.CompanyCD= string.Empty;
          this.UserID= string.Empty;
          this.OperateDate= DateTime.Now;
          this.ObjectID= string.Empty;
          this.ObjectName= string.Empty;
          this.Element= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? OperateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ModuleID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ObjectID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ObjectName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Element { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}