//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ProductInfoTemp : Entity
    {
        public ProductInfoTemp()
        {
          this.企业编号= string.Empty;
          this.物品编号= string.Empty;
          this.物品名称= string.Empty;
          this.名称简称= string.Empty;
          this.条码= string.Empty;
          this.单位= string.Empty;
          this.规格型号= string.Empty;
          this.颜色= string.Empty;
          this.产地= string.Empty;
          this.主放仓库= string.Empty;
          this.最低库存= string.Empty;
          this.最高库存= string.Empty;
          this.安全库存= string.Empty;
          this.去税售价= string.Empty;
          this.销项税率= string.Empty;
          this.进项税率= string.Empty;
          this.含税售价= string.Empty;
          this.含税进价= string.Empty;
          this.去税进价= string.Empty;
          this.物品分类= string.Empty;
          this.标准成本= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? 流水号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 企业编号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 物品编号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 物品名称 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 名称简称 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 条码 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 单位 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 规格型号 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 颜色 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 产地 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 主放仓库 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 最低库存 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 最高库存 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 安全库存 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 去税售价 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 销项税率 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 进项税率 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 含税售价 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 含税进价 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 去税进价 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 物品分类 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string 标准成本 { get; set; }

    }
}