//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ProductPriceChange : Entity
    {
        public ProductPriceChange()
        {
          this.ChangeNo= string.Empty;
          this.CompanyCD= string.Empty;
          this.Title= string.Empty;
          this.ChangeDate= DateTime.Now;
          this.Remark= string.Empty;
          this.BillStatus= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ConfirmDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string ChangeNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? StandardSell { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TaxRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SellTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Discount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? StandardSellNew { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TaxRateNew { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SellTaxNew { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? DiscountNew { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ChangeDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Chenger { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}