//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ProviderContactHistory : Entity
    {
        public ProviderContactHistory()
        {
          this.CompanyCD= string.Empty;
          this.CustID= string.Empty;
          this.ContactNo= string.Empty;
          this.Title= string.Empty;
          this.LinkManName= string.Empty;
          this.LinkDate= DateTime.Now;
          this.Contents= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ContactNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? LinkManID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LinkManName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? LinkReasonID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? LinkMode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? LinkDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Linker { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Contents { get; set; }

    }
}