//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PublicNotice : Entity
    {
        public PublicNotice()
        {
          this.CompanyCD= string.Empty;
          this.NewsTitle= string.Empty;
          this.NewsContent= string.Empty;
          this.IsShow= string.Empty;
          this.Status= string.Empty;
          this.ComfirmDate= DateTime.Now;
          this.CreateDate= DateTime.Now;
        }

        /// <summary>
	    /// 企业代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 标题
	    /// </summary>
        public string NewsTitle { get; set; }
        /// <summary>
	    /// 内容
	    /// </summary>
        public string NewsContent { get; set; }
        /// <summary>
	    /// 是否显示（0：否；1：是）
	    /// </summary>
        public string IsShow { get; set; }
        /// <summary>
	    /// 审核状态：0未审核，1已审核
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 确认人ID
	    /// </summary>
        public int? Comfirmor { get; set; }
        /// <summary>
	    /// 确认时间
	    /// </summary>
        public System.DateTime? ComfirmDate { get; set; }
        /// <summary>
	    /// 发布人ID（对应员工表ID）
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 发布时间（精确到秒）
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }

    }
}