//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PurchaseOrder : Entity
    {
        public PurchaseOrder()
        {
          this.CompanyCD= string.Empty;
          this.OrderNo= string.Empty;
          this.Title= string.Empty;
          this.FromType= string.Empty;
          this.PurchaseDate= DateTime.Now;
          this.OrderDate= DateTime.Now;
          this.TheyDelegate= string.Empty;
          this.ProviderBillID= string.Empty;
          this.Remark= string.Empty;
          this.IsAddTax= string.Empty;
          this.IsOpenbill= string.Empty;
          this.ConfirmDate= DateTime.Now;
          this.CloseDate= DateTime.Now;
          this.BillStatus= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Attachment= string.Empty;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
          this.IsFeesAccount= string.Empty;
          this.IsAccount= string.Empty;
          this.AccountDate= DateTime.Now;
          this.CanViewUser= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OrderNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? TypeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Rate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? PurchaseDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? OrderDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string TheyDelegate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? OurDelegate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProviderID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? PayType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? MoneyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Purchaser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? TakeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CarryType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProviderBillID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalFee { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Discount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? DiscountTotal { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? RealTotal { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsAddTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CountTotal { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsOpenbill { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Closer { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CloseDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BillStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 附件
	    /// </summary>
        public string Attachment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Othertotal { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField10 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsFeesAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? AccountDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Accountor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AttestBillID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProjectID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }

    }
}