//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PurchaseRequire : Entity
    {
        public PurchaseRequire()
        {
          this.CompanyCD= string.Empty;
          this.ProdNo= string.Empty;
          this.ProdName= string.Empty;
          this.Standards= string.Empty;
          this.RequireDate= DateTime.Now;
          this.CreateDate= DateTime.Now;
          this.ConfirmDate= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Mrpcd { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProdID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProdNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProdName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProdTypeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Standards { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? UnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? NeedCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? HasNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? WantingNum { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? WaitingDays { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? RequireDate { get; set; }
        /// <summary>
	    /// 已计划数量
	    /// </summary>
        public decimal? OrderCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }

    }
}