//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("RoleFunction")]
    public partial class RoleFunction : Entity
    {
        public RoleFunction()
        {
          this.CompanyCD= string.Empty;
          this.RoleID= 0;
          this.ModuleID= string.Empty;
            this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int RoleID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModuleID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FunctionID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }

    }
}