//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SalaryPerformanceRoyaltySet : Entity
    {
        public SalaryPerformanceRoyaltySet()
        {
          this.CompanyCD= string.Empty;
          this.ModifiedUserID= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.Taskflag= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? EmployeeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? MiniScore { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? MaxScore { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Confficent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Taskflag { get; set; }

    }
}