//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SalaryReportSummary : Entity
    {
        public SalaryReportSummary()
        {
          this.CompanyCD= string.Empty;
          this.ReprotNo= string.Empty;
          this.EmployeeID= 0;
          this.EmployeeNo= string.Empty;
          this.EmployeeName= string.Empty;
          this.DeptName= string.Empty;
          this.QuarterName= string.Empty;
          this.AdminLevelName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ReprotNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int EmployeeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? FixedMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? WorkMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TimeMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CommissionMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OtherGetMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? AllGetMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? IncomeTax { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? Insurance { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OtherKillMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? AllKillMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SalaryMoney { get; set; }
        /// <summary>
	    /// 员工编号
	    /// </summary>
        public string EmployeeNo { get; set; }
        /// <summary>
	    /// 员工姓名
	    /// </summary>
        public string EmployeeName { get; set; }
        /// <summary>
	    /// 员工所在部门
	    /// </summary>
        public string DeptName { get; set; }
        /// <summary>
	    /// 所在岗位
	    /// </summary>
        public string QuarterName { get; set; }
        /// <summary>
	    /// 岗位职等
	    /// </summary>
        public string AdminLevelName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? PerformanceMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? CompanyComMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? DeptComMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? PersonComMoney { get; set; }

    }
}