//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SalaryItem : Entity
    {
        public SalaryItem()
        {
          this.CompanyCD= string.Empty;
          this.ItemName= string.Empty;
          this.ItemOrder= 0;
          this.Calculate= string.Empty;
          this.PayFlag= string.Empty;
          this.ChangeFlag= string.Empty;
          this.UsedStatus= string.Empty;
          this.Remark= string.Empty;
          this.ParamsList= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ItemName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int ItemOrder { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Calculate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string PayFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ChangeFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ParamsList { get; set; }

    }
}