//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SellPlanDetail : Entity
    {
        public SellPlanDetail()
        {
          this.CompanyCD= string.Empty;
          this.PlanNo= string.Empty;
          this.DetailType= string.Empty;
          this.SummarizeDate= DateTime.Now;
          this.SummarizeNote= string.Empty;
          this.AimRealResult= string.Empty;
          this.AddOrCut= string.Empty;
          this.Difference= string.Empty;
          this.IsSummarize= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 计划编号
	    /// </summary>
        public string PlanNo { get; set; }
        /// <summary>
	    /// 明细种类（1.部门明细2.人员明细3.物品明细）
	    /// </summary>
        public string DetailType { get; set; }
        /// <summary>
	    /// 上级明细的id
	    /// </summary>
        public int? ParentID { get; set; }
        /// <summary>
	    /// 明细信息对应的部门、物品或人员id
	    /// </summary>
        public int? DetailID { get; set; }
        /// <summary>
	    /// 目标总金额
	    /// </summary>
        public decimal? DetailTotal { get; set; }
        /// <summary>
	    /// 最低目标额
	    /// </summary>
        public decimal? MinDetailotal { get; set; }
        /// <summary>
	    /// 总结时间
	    /// </summary>
        public System.DateTime? SummarizeDate { get; set; }
        /// <summary>
	    /// 总结内容
	    /// </summary>
        public string SummarizeNote { get; set; }
        /// <summary>
	    /// 总结人
	    /// </summary>
        public int? Summarizer { get; set; }
        /// <summary>
	    /// 目标实绩
	    /// </summary>
        public string AimRealResult { get; set; }
        /// <summary>
	    /// 完成情况（0低于目标值，1等于目标值，2超过目标值）
	    /// </summary>
        public string AddOrCut { get; set; }
        /// <summary>
	    /// 差额
	    /// </summary>
        public string Difference { get; set; }
        /// <summary>
	    /// 目标达成率%
	    /// </summary>
        public decimal? CompletePercent { get; set; }
        /// <summary>
	    /// 是否以总结（0否，1是）
	    /// </summary>
        public string IsSummarize { get; set; }

    }
}