//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SellChance : Entity
    {
        public SellChance()
        {
          this.CompanyCD= string.Empty;
          this.CustTel= string.Empty;
          this.ChanceNo= string.Empty;
          this.Title= string.Empty;
          this.FindDate= DateTime.Now;
          this.ProvideMan= string.Empty;
          this.Requires= string.Empty;
          this.IntendDate= DateTime.Now;
          this.Remark= string.Empty;
          this.IsQuoted= string.Empty;
          this.CanViewUser= string.Empty;
          this.CanViewUserName= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
          this.IsMobileNotice= string.Empty;
          this.RemindTime= DateTime.Now;
          this.RemindMTel= string.Empty;
          this.RemindContent= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CustTel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ChanceNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ChanceType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? HapSource { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Seller { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SellDeptId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? FindDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProvideMan { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Requires { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? IntendDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? IntendMoney { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsQuoted { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField10 { get; set; }
        /// <summary>
	    /// 是否手机短信提醒（0否，1是）
	    /// </summary>
        public string IsMobileNotice { get; set; }
        /// <summary>
	    /// 提醒时间
	    /// </summary>
        public System.DateTime? RemindTime { get; set; }
        /// <summary>
	    /// 提醒手机号
	    /// </summary>
        public string RemindMTel { get; set; }
        /// <summary>
	    /// 提醒内容
	    /// </summary>
        public string RemindContent { get; set; }
        /// <summary>
	    /// 接收人
	    /// </summary>
        public int? ReceiverID { get; set; }

    }
}