//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SellBack : Entity
    {
        public SellBack()
        {
          this.CompanyCD= string.Empty;
          this.Title= string.Empty;
          this.BackNo= string.Empty;
          this.FromType= string.Empty;
          this.CustTel= string.Empty;
          this.BusiType= string.Empty;
          this.BackDate= DateTime.Now;
          this.SendAddress= string.Empty;
          this.ReceiveAddress= string.Empty;
          this.IsAddTax= string.Empty;
          this.Remark= string.Empty;
          this.BillStatus= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ConfirmDate= DateTime.Now;
          this.CloseDate= DateTime.Now;
          this.IsOpenbill= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.ExtField1= string.Empty;
          this.ExtField2= string.Empty;
          this.ExtField3= string.Empty;
          this.ExtField4= string.Empty;
          this.ExtField5= string.Empty;
          this.ExtField6= string.Empty;
          this.ExtField7= string.Empty;
          this.ExtField8= string.Empty;
          this.ExtField9= string.Empty;
          this.ExtField10= string.Empty;
          this.IsFeesAccount= string.Empty;
          this.IsAccount= string.Empty;
          this.AccountDate= DateTime.Now;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 主题
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 退货单编号
	    /// </summary>
        public string BackNo { get; set; }
        /// <summary>
	    /// 客户ID（关联客户信息表）
	    /// </summary>
        public int? CustID { get; set; }
        /// <summary>
	    /// 来源单据类型（0无来源，1发货通知单）
	    /// </summary>
        public string FromType { get; set; }
        /// <summary>
	    /// 来源单据ID（发货通知单）
	    /// </summary>
        public int? FromBillID { get; set; }
        /// <summary>
	    /// 客户联系电话
	    /// </summary>
        public string CustTel { get; set; }
        /// <summary>
	    /// 业务类型（1普通销售,2委托代销,3直运，4零售，5销售调拨，6分期付款）
	    /// </summary>
        public string BusiType { get; set; }
        /// <summary>
	    /// 退货日期
	    /// </summary>
        public System.DateTime? BackDate { get; set; }
        /// <summary>
	    /// 业务员(对应员工表ID)
	    /// </summary>
        public int? Seller { get; set; }
        /// <summary>
	    /// 部门(对部门表ID)
	    /// </summary>
        public int? SellDeptId { get; set; }
        /// <summary>
	    /// 运送方式ID
	    /// </summary>
        public int? CarryType { get; set; }
        /// <summary>
	    /// 发货地址
	    /// </summary>
        public string SendAddress { get; set; }
        /// <summary>
	    /// 收货地址
	    /// </summary>
        public string ReceiveAddress { get; set; }
        /// <summary>
	    /// 结算方式ID
	    /// </summary>
        public int? PayType { get; set; }
        /// <summary>
	    /// 支付方式ID
	    /// </summary>
        public int? MoneyType { get; set; }
        /// <summary>
	    /// 币种ID
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 汇率
	    /// </summary>
        public decimal? Rate { get; set; }
        /// <summary>
	    /// 是否增值税（0否,1是
	    /// </summary>
        public string IsAddTax { get; set; }
        /// <summary>
	    /// 金额合计
	    /// </summary>
        public decimal? TotalPrice { get; set; }
        /// <summary>
	    /// 税额合计
	    /// </summary>
        public decimal? Tax { get; set; }
        /// <summary>
	    /// 含税金额合计
	    /// </summary>
        public decimal? TotalFee { get; set; }
        /// <summary>
	    /// 整单折扣（%）
	    /// </summary>
        public decimal? Discount { get; set; }
        /// <summary>
	    /// 折扣金额
	    /// </summary>
        public decimal? DiscountTotal { get; set; }
        /// <summary>
	    /// 折后含税金额合计
	    /// </summary>
        public decimal? RealTotal { get; set; }
        /// <summary>
	    /// 退货数量合计
	    /// </summary>
        public decimal? CountTotal { get; set; }
        /// <summary>
	    /// 抵应收账款
	    /// </summary>
        public decimal? NotPayTotal { get; set; }
        /// <summary>
	    /// 应退货款总额
	    /// </summary>
        public decimal? BackTotal { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 单据状态（1制单，2执行，3变更，4手工结单，5自动结单）
	    /// </summary>
        public string BillStatus { get; set; }
        /// <summary>
	    /// 制单人ID
	    /// </summary>
        public int? Creator { get; set; }
        /// <summary>
	    /// 制单日期
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 确认人ID
	    /// </summary>
        public int? Confirmor { get; set; }
        /// <summary>
	    /// 确认日期
	    /// </summary>
        public System.DateTime? ConfirmDate { get; set; }
        /// <summary>
	    /// 结单人ID
	    /// </summary>
        public int? Closer { get; set; }
        /// <summary>
	    /// 结单日期
	    /// </summary>
        public System.DateTime? CloseDate { get; set; }
        /// <summary>
	    /// 是否开票
	    /// </summary>
        public string IsOpenbill { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID(对应操作用户UserID)
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField4 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField5 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField6 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ExtField10 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsFeesAccount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProjectID { get; set; }
        /// <summary>
	    /// 是否登记凭证
	    /// </summary>
        public string IsAccount { get; set; }
        /// <summary>
	    /// 登记时间
	    /// </summary>
        public System.DateTime? AccountDate { get; set; }
        /// <summary>
	    /// 登记凭证人
	    /// </summary>
        public int? Accountor { get; set; }
        /// <summary>
	    /// 生成凭证ID
	    /// </summary>
        public int? AttestBillID { get; set; }

    }
}