//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ServWarehouse : Entity
    {
        public ServWarehouse()
        {
          this.InfoNo= string.Empty;
          this.TypeID= 0;
          this.ProfessionType= string.Empty;
          this.InfoTitle= string.Empty;
          this.InfoFlag= string.Empty;
          this.Keyword= string.Empty;
          this.Content= string.Empty;
          this.IsShow= string.Empty;
          this.SourceFrom= string.Empty;
          this.SafeLevel= string.Empty;
          this.InfoName= string.Empty;
          this.Company= string.Empty;
          this.City= string.Empty;
          this.InfoIntro= string.Empty;
          this.ContractName= string.Empty;
          this.Tel= string.Empty;
          this.Email= string.Empty;
          this.WebSite= string.Empty;
          this.Others= string.Empty;
          this.Remark= string.Empty;
          this.Attachment= string.Empty;
          this.CreateUserID= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string InfoNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int TypeID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ProfessionType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InfoTitle { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InfoFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Keyword { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Content { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsShow { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SourceFrom { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SafeLevel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InfoName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Company { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string City { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InfoIntro { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ContractName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Tel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Email { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string WebSite { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Others { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Attachment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ExpireDays { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}