//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class StorageInfo : Entity
    {
        public StorageInfo()
        {
          this.CompanyCD= string.Empty;
          this.StorageNo= string.Empty;
          this.StorageName= string.Empty;
          this.StorageType= string.Empty;
          this.UsedStatus= string.Empty;
          this.Remark= string.Empty;
          this.CanViewUser= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string StorageNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string StorageName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string StorageType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CanViewUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? StorageAdmin { get; set; }

    }
}