//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class StorageDaily : Entity
    {
        public StorageDaily()
        {
          this.Id= 0;
          this.CompanyCD= string.Empty;
          this.DailyDate= DateTime.Now;
          this.BatchNo= string.Empty;
          this.Remark= string.Empty;
          this.CreateDate= DateTime.Now;
        }

        /// <summary>
	    /// ID，自动生成
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 公司编码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 日结日期
	    /// </summary>
        public System.DateTime? DailyDate { get; set; }
        /// <summary>
	    /// 物品ID
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 仓库ID
	    /// </summary>
        public int? StorageID { get; set; }
        /// <summary>
	    /// 批次
	    /// </summary>
        public string BatchNo { get; set; }
        /// <summary>
	    /// 期初库存录入数量
	    /// </summary>
        public decimal? InitInCount { get; set; }
        /// <summary>
	    /// 期初库存导入数量
	    /// </summary>
        public decimal? InitBatchCount { get; set; }
        /// <summary>
	    /// 采购入库数量
	    /// </summary>
        public decimal? PhurInCount { get; set; }
        /// <summary>
	    /// 生产完工入库数量
	    /// </summary>
        public decimal? MakeInCount { get; set; }
        /// <summary>
	    /// 销售退货入库数量
	    /// </summary>
        public decimal? SaleBackInCount { get; set; }
        /// <summary>
	    /// 门店销售退货入库数量（针对总店发货模式）
	    /// </summary>
        public decimal? SubSaleBackInCount { get; set; }
        /// <summary>
	    /// 红冲入库数量
	    /// </summary>
        public decimal? RedInCount { get; set; }
        /// <summary>
	    /// 其他入库数量
	    /// </summary>
        public decimal? OtherInCount { get; set; }
        /// <summary>
	    /// 借货返还数量
	    /// </summary>
        public decimal? BackInCount { get; set; }
        /// <summary>
	    /// 生产退料数量
	    /// </summary>
        public decimal? TakeInCount { get; set; }
        /// <summary>
	    /// 库存调拨入库数量
	    /// </summary>
        public decimal? DispInCount { get; set; }
        /// <summary>
	    /// 配送退货入库数量
	    /// </summary>
        public decimal? SendInCount { get; set; }
        /// <summary>
	    /// 销售出库数量
	    /// </summary>
        public decimal? SaleOutCount { get; set; }
        /// <summary>
	    /// 门店销售数量（针对总店发货模式）
	    /// </summary>
        public decimal? SubSaleOutCount { get; set; }
        /// <summary>
	    /// 采购退货出库数量
	    /// </summary>
        public decimal? PhurBackOutCount { get; set; }
        /// <summary>
	    /// 红冲出库数量
	    /// </summary>
        public decimal? RedOutCount { get; set; }
        /// <summary>
	    /// 其他出库数量
	    /// </summary>
        public decimal? OtherOutCount { get; set; }
        /// <summary>
	    /// 库存调拨出库数量
	    /// </summary>
        public decimal? DispOutCount { get; set; }
        /// <summary>
	    /// 借出数量
	    /// </summary>
        public decimal? LendCount { get; set; }
        /// <summary>
	    /// 库存调整数量（调减记为负数，调增记为正数。正数当入库，负数当出库）
	    /// </summary>
        public decimal? AdjustCount { get; set; }
        /// <summary>
	    /// 库存报损数量
	    /// </summary>
        public decimal? BadCount { get; set; }
        /// <summary>
	    /// 盘点调整数量（盘亏记负，盘盈记正。正数当入库，负数当出库）
	    /// </summary>
        public decimal? CheckCount { get; set; }
        /// <summary>
	    /// 领料出库数量
	    /// </summary>
        public decimal? TakeOutCount { get; set; }
        /// <summary>
	    /// 配送出库数量
	    /// </summary>
        public decimal? SendOutCount { get; set; }
        /// <summary>
	    /// 入库总数量（等于前面所有入库数量字段的累加减去红冲入库数量）
	    /// </summary>
        public decimal? InTotal { get; set; }
        /// <summary>
	    /// 出库总数量（等于前面所有出库数量字段的累加减去红冲出库数量）
	    /// </summary>
        public decimal? OutTotal { get; set; }
        /// <summary>
	    /// 当日结存量 
	    /// </summary>
        public decimal? TodayCount { get; set; }
        /// <summary>
	    /// 当日销售金额
	    /// </summary>
        public decimal? SaleFee { get; set; }
        /// <summary>
	    /// 当日销售退货金额
	    /// </summary>
        public decimal? SaleBackFee { get; set; }
        /// <summary>
	    /// 当日采购金额
	    /// </summary>
        public decimal? PhurFee { get; set; }
        /// <summary>
	    /// 当日采购退货金额
	    /// </summary>
        public decimal? PhurBackFee { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 操作日期
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 操作人(手工日结的取当前登录人的ID,自动日结的默认为0)
	    /// </summary>
        public int? Creator { get; set; }

    }
}