//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class StorageProduct : Entity
    {
        public StorageProduct()
        {
          this.CompanyCD= string.Empty;
          this.ProductID= 0;
          this.BatchNo= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? StorageID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int ProductID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeptID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ProductCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OrderCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? RoadCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OutCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? InCount { get; set; }
        /// <summary>
	    /// 批次
	    /// </summary>
        public string BatchNo { get; set; }

    }
}