//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SubjectsBeginDate : Entity
    {
        public SubjectsBeginDate()
        {
          this.CompanyCD= string.Empty;
          this.BeginDate= DateTime.Now;
        }

        /// <summary>
	    /// 公司编码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime BeginDate { get; set; }

    }
}