//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class SubjectsBeginDetails : Entity
    {
        public SubjectsBeginDetails()
        {
          this.CompanyCD= string.Empty;
          this.SubjectsCD= string.Empty;
          this.Dirt= string.Empty;
          this.SubjectsDetails= string.Empty;
          this.FormTBName= string.Empty;
          this.FileName= string.Empty;
        }

        /// <summary>
	    /// 企业编码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 科目代码
	    /// </summary>
        public string SubjectsCD { get; set; }
        /// <summary>
	    /// 方向
	    /// </summary>
        public string Dirt { get; set; }
        /// <summary>
	    /// 本年累计借方
	    /// </summary>
        public decimal? YTotalDebit { get; set; }
        /// <summary>
	    /// 本年累计贷方
	    /// </summary>
        public decimal? YTotalLenders { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? OriginalCurrency { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? StandardCurrency { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BeginMoney { get; set; }
        /// <summary>
	    /// 币种
	    /// </summary>
        public int? CurrencyType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? SumOriginalCurrency { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? YTotalDebitY { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? YTotalLendersY { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SubjectsDetails { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FormTBName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FileName { get; set; }

    }
}