//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class TableExtFields : Entity
    {
        public TableExtFields()
        {
          this.FunctionModule= string.Empty;
          this.ModelNo= string.Empty;
          this.TabName= string.Empty;
          this.CompanyCD= string.Empty;
          this.EFIndex= 0;
          this.EFDesc= string.Empty;
          this.EFType= string.Empty;
          this.EFValueList= string.Empty;
        }

        /// <summary>
	    /// 功能模块
	    /// </summary>
        public string FunctionModule { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModelNo { get; set; }
        /// <summary>
	    /// 扩展的表名
	    /// </summary>
        public string TabName { get; set; }
        /// <summary>
	    /// 企业代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 字段索引
	    /// </summary>
        public int EFIndex { get; set; }
        /// <summary>
	    /// 字段描述
	    /// </summary>
        public string EFDesc { get; set; }
        /// <summary>
	    /// 控件类型（1-TextBox,2-Select）
	    /// </summary>
        public string EFType { get; set; }
        /// <summary>
	    /// Select控件对应 的可选值列表（逗号分隔）
	    /// </summary>
        public string EFValueList { get; set; }

    }
}