//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class TechnicsRoutingDetail : Entity
    {
        public TechnicsRoutingDetail()
        {
          this.CompanyCD= string.Empty;
          this.RouteNo= string.Empty;
          this.SequID= 0;
          this.Wcid= 0;
          this.TimeUnit= string.Empty;
          this.Isoutsource= string.Empty;
          this.CheckWay= string.Empty;
          this.Remark= string.Empty;
          this.UsedStatus= string.Empty;
          this.IsCharge= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string RouteNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProcSequNumber { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int SequID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int Wcid { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string TimeUnit { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Isoutsource { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CheckWay { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TimeWage { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? PieceWage { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UsedStatus { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ReadyTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? RunTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsCharge { get; set; }

    }
}