//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class UnitGroup : Entity
    {
        public UnitGroup()
        {
          this.Id= 0;
          this.CompanyCD= string.Empty;
          this.GroupUnitNo= string.Empty;
          this.GroupUnitName= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 主键,自动生成
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 企业代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 计量单位组编号
	    /// </summary>
        public string GroupUnitNo { get; set; }
        /// <summary>
	    /// 计量单位组名
	    /// </summary>
        public string GroupUnitName { get; set; }
        /// <summary>
	    /// 基本计量单位ID(对应计量单位表)
	    /// </summary>
        public int? BaseUnitID { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }

    }
}