//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class VoucherTemplateDetail : Entity
    {
        public VoucherTemplateDetail()
        {
          this.CompanyCD= string.Empty;
          this.TemNo= string.Empty;
          this.SubjectsNo= string.Empty;
          this.Direction= string.Empty;
          this.Remark= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int? SortNo { get; set; }
        /// <summary>
	    /// 公司编号
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 模板编号
	    /// </summary>
        public string TemNo { get; set; }
        /// <summary>
	    /// 科目编码
	    /// </summary>
        public string SubjectsNo { get; set; }
        /// <summary>
	    /// 金额所在方向（0借，1贷）
	    /// </summary>
        public string Direction { get; set; }
        /// <summary>
	    /// 金额所占比例
	    /// </summary>
        public decimal? Scale { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }

    }
}