//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WebStieSellOrder : Entity
    {
        public WebStieSellOrder()
        {
          this.CompanyCD= string.Empty;
          this.OrderNo= string.Empty;
          this.Title= string.Empty;
          this.OrderDate= DateTime.Now;
          this.ConsignmentDate= DateTime.Now;
          this.Status= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? CustomID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? LoginID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OrderNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Title { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? OrderDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ConsignmentDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Status { get; set; }

    }
}