//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WebSiteCustomInfo : Entity
    {
        public WebSiteCustomInfo()
        {
          this.Id= 0;
          this.CustomID= 0;
          this.LoginUserName= string.Empty;
          this.LoginPassword= string.Empty;
          this.Status= string.Empty;
          this.IsMember= string.Empty;
        }

        /// <summary>
	    /// 主键，自动生成
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 往来单位ID
	    /// </summary>
        public int CustomID { get; set; }
        /// <summary>
	    /// 站点登陆用户名
	    /// </summary>
        public string LoginUserName { get; set; }
        /// <summary>
	    /// 站点登陆密码
	    /// </summary>
        public string LoginPassword { get; set; }
        /// <summary>
	    /// 状态1 启用0 禁用
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 是否会员1 是0 否
	    /// </summary>
        public string IsMember { get; set; }

    }
}