//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WebSiteSellOrderDetail : Entity
    {
        public WebSiteSellOrderDetail()
        {
          this.OrderNo= string.Empty;
          this.CompanyCD= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string OrderNo { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? BaseUnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BasePrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? BaseCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? UsedUnitID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? UsedCount { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? UsedPrice { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? ExRate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public decimal? TotalPrice { get; set; }

    }
}