//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WebSiteProductInfo : Entity
    {
        public WebSiteProductInfo()
        {
          this.Id= 0;
          this.Description= string.Empty;
          this.ImgDIr= string.Empty;
          this.Status= string.Empty;
          this.DiscountStatus= string.Empty;
        }

        /// <summary>
	    /// 主键，自动生成
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 物品ID,对应表Officedba.ProductInfo
	    /// </summary>
        public int? ProductID { get; set; }
        /// <summary>
	    /// 商品描述
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 商品价格
	    /// </summary>
        public decimal? Price { get; set; }
        /// <summary>
	    /// 图片路径
	    /// </summary>
        public string ImgDIr { get; set; }
        /// <summary>
	    /// 状态1 启用0 禁用
	    /// </summary>
        public string Status { get; set; }
        /// <summary>
	    /// 折扣状态1 启用0 禁用
	    /// </summary>
        public string DiscountStatus { get; set; }

    }
}