//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WorkGroup : Entity
    {
        public WorkGroup()
        {
          this.CompanyCD= string.Empty;
          this.WorkGroupNo= string.Empty;
          this.WorkGroupName= string.Empty;
          this.WorkGroupType= string.Empty;
          this.WorkShiftNo= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 班组编号
	    /// </summary>
        public string WorkGroupNo { get; set; }
        /// <summary>
	    /// 班组名称
	    /// </summary>
        public string WorkGroupName { get; set; }
        /// <summary>
	    /// 班组类型
	    /// </summary>
        public string WorkGroupType { get; set; }
        /// <summary>
	    /// 对应班次号
	    /// </summary>
        public string WorkShiftNo { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}