//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WorkPlan : Entity
    {
        public WorkPlan()
        {
          this.CompanyCD= string.Empty;
          this.WorkGroupNo= string.Empty;
          this.WorkShiftIndex= string.Empty;
          this.WorkShiftNo= string.Empty;
          this.WorkPlanStartDate= DateTime.Now;
          this.WorkPlanEndDate= DateTime.Now;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
          this.IsRestDay= string.Empty;
        }

        /// <summary>
	    /// 公司代码
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 班组编号
	    /// </summary>
        public string WorkGroupNo { get; set; }
        /// <summary>
	    /// 对应班次序号
	    /// </summary>
        public string WorkShiftIndex { get; set; }
        /// <summary>
	    /// 对应班次编号
	    /// </summary>
        public string WorkShiftNo { get; set; }
        /// <summary>
	    /// 排班开始日
	    /// </summary>
        public System.DateTime? WorkPlanStartDate { get; set; }
        /// <summary>
	    /// 排班结束日
	    /// </summary>
        public System.DateTime? WorkPlanEndDate { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string IsRestDay { get; set; }

    }
}