//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Repository.Core;

namespace Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WorkShiftTime : Entity
    {
        public WorkShiftTime()
        {
          this.WorkShiftNo= string.Empty;
          this.ShiftTimeName= string.Empty;
          this.OnTime= string.Empty;
          this.IfAttendance= string.Empty;
          this.IfFlag= string.Empty;
          this.OffTime= string.Empty;
          this.CompanyCD= string.Empty;
          this.ModifiedDate= DateTime.Now;
          this.ModifiedUserID= string.Empty;
        }

        /// <summary>
	    /// 班次编号（对应班次设置表中WorkShiftNo）
	    /// </summary>
        public string WorkShiftNo { get; set; }
        /// <summary>
	    /// 班段名称
	    /// </summary>
        public string ShiftTimeName { get; set; }
        /// <summary>
	    /// 上班时间
	    /// </summary>
        public string OnTime { get; set; }
        /// <summary>
	    /// 上班可提前
	    /// </summary>
        public int? OnForwordTime { get; set; }
        /// <summary>
	    /// 上班可迟到
	    /// </summary>
        public int? OnLateTime { get; set; }
        /// <summary>
	    /// 是否考勤
	    /// </summary>
        public string IfAttendance { get; set; }
        /// <summary>
	    /// 是否跨日
	    /// </summary>
        public string IfFlag { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string OffTime { get; set; }
        /// <summary>
	    /// 下班可早退
	    /// </summary>
        public int? OffForwordTime { get; set; }
        /// <summary>
	    /// 下班可推迟
	    /// </summary>
        public int? OffLateTime { get; set; }
        /// <summary>
	    /// 考勤总工时（分）
	    /// </summary>
        public int? AttendanceTimeLong { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CompanyCD { get; set; }
        /// <summary>
	    /// 最后更新日期
	    /// </summary>
        public System.DateTime? ModifiedDate { get; set; }
        /// <summary>
	    /// 最后更新用户ID
	    /// </summary>
        public string ModifiedUserID { get; set; }

    }
}